version: "3"

volumes:
  db:
  redis:

services:
  daily-mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gateway
      MYSQL_PASSWORD: root
    command: --log-bin=mysqld-bin --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis:6
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6380:6379"
